[package]
name = "rust_libsysinfo"
version = "0.1.0"
authors = ["Protik Banerji <protik09@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"